# action.yml
name: 'haskell-stan'
author: "Kowainik — Veronika Romashkina, Dmitrii Kovanikov"
description: 'Haskell Static Analyser'
inputs:
  ghc-version:
    description: 'GHC version'
    required: false
    default: '8.8.3'
  stan-version:
    description: 'Stan version'
    required: false
    default: '0.0.1.0'
outputs:
  stanPath:
    description: 'Path to Stan inside Docker container'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.ghc-version }}
    - ${{ inputs.stan-version }}
# post-entrypoint: 'copy_release.sh'

branding:
  color: yellow
  icon: search
